baseURL: http://bytehubplus.github.io/
languageCode: zh-CN
title: Bytehub+ Open Source Commmunity
theme: ace
author:
  Wechat: richzhao
  email: zhao.zhenhua at gmail


menu:
  main:
    - identifier: home
      name: Home
      url: index

params:
  footer:
    - title: About
      content: >
        Bytehub+ 是社区驱动的、旨在提供敏感数据的保管、共享、协助开源项目。

enableGitInfo: true